#!/usr/bin/env bash

printf "*** COMPILING ***\n"
if arduino-cli compile --fqbn attiny:avr:ATtinyX5:cpu=attiny85,clock=internal8 $1; then
	printf "\n*** UPLOADING ***\n"
	arduino-cli upload -p /dev/ttyUSB0 -b attiny:avr:ATtinyX5:cpu=attiny85,clock=internal8 --programmer arduinoasisp $1 && echo "Success."
fi
